### PR TITLE
Fix JsonObject serializing/deserializing

### LINKED ISSUE #208: JSON value not encoded/decoded properly
If a producer sends a record with the following JSON in the HTTP body:

```json
{
	"records": [
		{
			"key": "key1",
			"value": { "foo": "bar", "aaa": 5 }
		}
	]
}
```

the consumer will get the following one:

```json
[
    {
        "topic": "test",
        "key": "key1",
        "value": {
            "map": {
                "foo": "bar",
                "aaa": 5
            },
            "empty": false
        },
        "partition": 0,
        "offset": 10
    }
]
```

where the "value" it's not exactly what expected.

### PR DESCRIPTION
**Pull request by ppatierno**
This PR fixes #208 .
We should need more unit tests for that but I am planning for a different PR for now.

### CODE REVIEW

File: src/main/resources/application.properties [hunk 1]
```diff
@@ -8,7 +8,7 @@ kafka.producer.acks=1
 kafka.consumer.auto.offset.reset=earliest
 
 #AMQP related settings
-amqp.enabled=true
+#amqp.enabled=true
```
Comment (tombentley) [inline src/main/resources/application.properties]: Does this change really belong in this PR?

File: src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java [hunk 2]
```diff
@@ -49,6 +47,7 @@
 import java.util.stream.Collectors;
 
 @RunWith(VertxUnitRunner.class)
+@SuppressWarnings("checkstyle:JavaNCSS")
```
Comment (tombentley) [inline src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java]: I think you should be able to annotate the method, rather than the whole class.

File: src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java [hunk 3]
```diff
@@ -2770,4 +2769,148 @@ public void formatAndAcceptMismatch(TestContext context) {
...
+
+        Async async = context.async();
+
+        JsonObject sentKey = new JsonObject()
+                .put("f1", "v1")
+                .put("array", new JsonArray().add(1).add(2));
+
+        JsonObject sentValue = new JsonObject()
+                .put("array", new JsonArray().add("v1").add("v2"))
+                .put("foo", "bar").put("number", 123);
```
Comment (tombentley) [inline src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java]: TBH I would like to see nested objects tested too.

File: src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java [hunk 4]
```diff
@@ -2770,4 +2769,148 @@ public void formatAndAcceptMismatch(TestContext context) {
...
+                    JsonObject jsonResponse = response.body().getJsonObject(0);
+
+                    String kafkaTopic = jsonResponse.getString("topic");
+                    int kafkaPartition = jsonResponse.getInteger("partition");
+                    JsonObject key = jsonResponse.getJsonObject("key");
+                    JsonObject value = jsonResponse.getJsonObject("value");
+                    long offset = jsonResponse.getLong("offset");
+
+                    context.assertEquals(topic, kafkaTopic);
+                    context.assertTrue(sentValue.equals(value));
```
Comment (tombentley) [inline src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java]: `assertEquals()` would be more conventional.

File: src/main/resources/application.properties (hunk 1 above)
Comment (ppatierno) [reply src/main/resources/application.properties]: No you are right, I was testing offline with postman and removed the AMQP stuff.

File: src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java (hunk 2 above)
Comment (ppatierno) [reply src/test/java/io/strimzi/kafka/bridge/http/HttpBridgeTest.java]: Reading about the metric I think that in this case it's about the whole class which is becoming quite big even if QE people are working on having it better.
