### PR TITLE
Fixing missing handling not existing resources

### LINKED ISSUE #394: Message "null" when hitting a not existing resource
When the HTTP client sends a request to a non existing resource (i.e. `curl http://localhost:8080/` or `curl http://localhost:8080/not-existing`), the bridge replies with the following JSON:

```json
{"error_code":404,"message":null}
```

it contains the `404` error code but not the related message (i.e. Not Found in this case).

### PR DESCRIPTION
**Pull request by ppatierno**
This PR fixes #394

### CODE REVIEW

File: src/main/java/io/strimzi/kafka/bridge/http/HttpBridge.java [hunk 1]
```diff
@@ -409,25 +409,30 @@ private void errorHandler(RoutingContext routingContext) {
...
+                if (validationException.parameterName() != null) {
+                    sb.append("Validation error on: " + validationException.parameterName() + " - ");
+                }
+                sb.append(validationException.getMessage());
+                message = sb.toString();
             }
-            sb.append(validationException.getMessage());
-            message = sb.toString();
+        } else if (routingContext.statusCode() == HttpResponseStatus.NOT_FOUND.code()) {
+            message = HttpResponseStatus.NOT_FOUND.reasonPhrase();
```
Comment (tombentley) [inline src/main/java/io/strimzi/kafka/bridge/http/HttpBridge.java]: Why do you only set the non-null message for NOT_FOUND and BAD_REQUEST?

Comment (ppatierno) [reply src/main/java/io/strimzi/kafka/bridge/http/HttpBridge.java]: The error handler is set on the Vertx route only for these two errors. It means we are sure that it's called only in this two cases. All the others follow the normal flow.
