### PR TITLE
Fix HTTP sink endpoint removing on connection close

### LINKED ISSUE #189: Wrong map key is used to remove HTTP sink endpoint on close
If for any reason, the close happens on the sink and the related handler is called, the wrong key is used to remove the HTTP sink from the related collection.

```java
sink.closeHandler(s -> {
            httpBridgeContext.getHttpSinkEndpoints().remove(sink);
        });
```

The handler or the sink itself should expose somehow the consumer id which is used as key for that collection.

### PR DESCRIPTION
**Pull request by ppatierno**
This PR fixes #189 

Added sink and source name
Fixed bug on removing HTTP sink endpoint (based on name/consumer-id)

### CODE REVIEW

File: src/main/java/io/strimzi/kafka/bridge/http/HttpSinkBridgeEndpoint.java [hunk 1]
```diff
@@ -304,10 +304,9 @@ public void handle(Endpoint<?> endpoint, Handler<?> handler) {
 
                 JsonObject json = bodyAsJson;
                 // if no name, a random one is assigned
-                String consumerInstanceId = json.getString("name",
-                        "kafka-bridge-consumer-" + UUID.randomUUID().toString());
+                this.name = json.getString("name", "kafka-bridge-consumer-" + UUID.randomUUID().toString());
```
Comment (tombentley) [inline src/main/java/io/strimzi/kafka/bridge/http/HttpSinkBridgeEndpoint.java]: The string concat will invoke toString anyway

```suggestion
                this.name = json.getString("name", "kafka-bridge-consumer-" + UUID.randomUUID());
```

File: src/main/java/io/strimzi/kafka/bridge/http/HttpSourceBridgeEndpoint.java [hunk 2]
```diff
@@ -41,6 +42,12 @@ public HttpSourceBridgeEndpoint(Vertx vertx, HttpBridgeConfig bridgeConfigProper
         this.httpBridgeContext = httpBridgeContext;
     }
 
+    @Override
+    public void open() {
+        this.name = "kafka-bridge-producer-" + UUID.randomUUID().toString();
```
Comment (tombentley) [inline src/main/java/io/strimzi/kafka/bridge/http/HttpSourceBridgeEndpoint.java]:
```suggestion
        this.name = "kafka-bridge-producer-" + UUID.randomUUID();
```
